# CI de Nível 04 - Pipeline Integrada ao Build do Código

# nome da pipeline
name: 'N4 - Execução Integrada'

# gatilhos / triggers - regras de disparo
# gatilho manual = workflow_dispatch
# gatilho de agendamento = schedule
# gatilho de Execução por deploy = workflow_run
# gatilho de Execução Integrada = workflow_dispatch

on:
  workflow_dispatch:

#tarefas dentro da pipeline = jobs

jobs:
  #nome do job
  inspecao:
    # maquina onde o job vai rodar
    runs-on: ubuntu-latest

    # passos do job
    steps:
      # clone do projeto
      - uses: actions/checkout@v6

      # instalção do node
      - uses: actions/setup-node@v6
        with:
          node-version: latest

      # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      #   instalação das dependências
      - name: Instalando dependências
        run: yarn

      - name: Inspeção de Código
        run: yarn lint

  unidade:
    runs-on: ubuntu-latest
    needs: [inspecao]

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Rodando testes unitários
        run: yarn run test

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [inspecao]

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: Instalando yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Browsers do Playwright
        run: yarn playwright install

      - name: Executando testes e2e
        run: yarn run e2e

  mutation-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: Instalando yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Executando os testes de mutação
        run: yarn run test:mutation

  deploy:
    runs-on: ubuntu-latest
    needs: [unidade, e2e-tests]

    steps:
      - name: Simulação de Deploy
        run: echo 'Deploy sendo realizado...'
